### ISSUE TITLE
RateIt moved to GitHub

### ISSUE THREAD

**Issue by gjunge** [Nimmer/rateit-npm#1]
Hi,

RateIt finally moved to GitHub, and now has also it's own npm package: jquery.rateit
So if you want you can move over to the official package, and always with the latest version, and remove confusion for other users.

Thanks for the push of getting RateIt finally over to GitHub and into npm (bower is on its way as well).

Gidon

**Comment by Nimmer** [comment]
Hello,
that is great to hear! I will now use the official package. I checked your git repository and strongly recommend adding a little header for npm and bower installation (just like https://github.com/twbs/bootstrap#quick-start) 
I will now remove my repository from Github
Good luck with your plugin,
Matus

**Comment by gjunge** [comment]
Done. Thanks for the tip!
